#!/usr/bin/env bash

# Test whether a command exists
# $1 - cmd to test
# - https://github.com/necolas/dotfiles
type_exists() {
    if [ $(type -P $1) ]; then
      return 0
    fi
    return 1
}

# Setup the $os and $distro
# See: http://linuxmafia.com/faq/Admin/release-files.html
check_os() {
    case $OSTYPE in
      darwin*)
        os="osx"
        if [ $(compare_versions "$(sw_vers -productVersion)" "10.9") == '<' ]; then
            log_error "OS X 10.9.0+ required"
            return 1
        fi
        ;;
      linux*)
        os="linux"
        if [[ -e "/etc/lsb-release" ]]; then
            distro="ubuntu" 
        elif [[ -e "/etc/debian_release" || -e "/etc/debian_version" ]]; then
            distro="debian"
        elif [[ -e "/etc/redhat-release" || -e "/etc/redhat-version" ]]; then
            distro="redhat"
        elif [[ -e "/etc/fedora-release" ]]; then
            distro="fedora"
        else
            log_error "Unsupported linux distro"
            return 1
        fi
        ;;
      *)
        log_error "Unsupported OS"
        return 1
        ;;
    esac
    return 0
}
