#!/usr/bin/env bash

setup_sudo() {
    local need_sudo=${1:-false}

    if [[ $need_sudo == false ]]; then
        case $os in
            osx)
                is_xcode_installed \
                && is_brew_installed \
                && is_bash4 \
                && return
                ;;
            *) ;; #todo
        esac
    fi

    # Ask for the administrator password upfront and keep-alive until finished
    # NOTE: installing homebrew will invalidate the keep-alive :(
    sudo -v -p "This script requires sudo for some operations. Password:"
    while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
}

# Test whether a command exists
# $1 - cmd to test
# - https://github.com/necolas/dotfiles
type_exists() {
    if [ $(type -P $1) ]; then
        return 0
    fi
    return 1
}

# Setup the $os and $distro
# See: http://linuxmafia.com/faq/Admin/release-files.html
setup_os() {
    case $OSTYPE in
        darwin*)
            os="osx"
            ;;
        linux*)
            os="linux"
            if [[ -e "/etc/lsb-release" ]]; then
                distro="ubuntu"
            elif [[ -e "/etc/debian_release" || -e "/etc/debian_version" ]]; then
                distro="debian"
            elif [[ -e "/etc/redhat-release" || -e "/etc/redhat-version" ]]; then
                distro="redhat"
            elif [[ -e "/etc/fedora-release" ]]; then
                distro="fedora"
            else
                log_error "Unsupported linux distro"
                return 1
            fi
            ;;
        *)
            log_error "Unsupported OS"
            return 1
            ;;
    esac
    return 0
}
